name: main

on: [push, pull_request]


jobs:
  main:
    name: "Pull Request Docs Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: doc/_build/html/
